image_wall_api:
    resource: "@ImageWallApiBundle/Resources/config/routing.yml"
    prefix:   /api

image_wall_core:
    resource: "@ImageWallCoreBundle/Resources/config/routing.yml"
    prefix:   /

image_wall_web:
    resource: "@ImageWallWebBundle/Resources/config/routing.yml"
    prefix:   /
