ImageWall\CoreBundle\Entity\Post:
    type: entity
    table: Post
    uniqueConstraints:
        post_id_UNIQUE:
            columns:
                - post_id
    id:
        postId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: post_id
            generator:
                strategy: IDENTITY
    fields:
        usrId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: usr_id
        title:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        img:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
