-- MySQL Script generated by MySQL Workbench
-- Mon Aug 22 19:27:40 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ImageWall
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ImageWall` ;

-- -----------------------------------------------------
-- Schema ImageWall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ImageWall` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `ImageWall` ;

-- -----------------------------------------------------
-- Table `Post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Post` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Post` (
  `post_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `usr_id` INT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NULL,
  `img` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`post_id`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `post_id_UNIQUE` ON `Post` (`post_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
